-- PostgreSQL schema for Supabase. This file creates structure only; no demo data.
-- Runtime selects this backend when DATABASE_BACKEND=supabase.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    student_code TEXT UNIQUE,
    preferred_language TEXT DEFAULT 'vi',
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS speaker_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id),
    embedding vector(192) NOT NULL,
    num_samples INTEGER NOT NULL,
    model_version TEXT NOT NULL,
    enrollment_method TEXT DEFAULT 'mean',
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS enrollment_samples (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    audio_path TEXT NOT NULL,
    sentence_id INTEGER,
    sentence_text TEXT,
    selection_method TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    subject TEXT NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ,
    location TEXT
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    title TEXT NOT NULL,
    due_date TIMESTAMPTZ,
    status TEXT DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS private_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    title TEXT,
    content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS course_rooms (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject TEXT NOT NULL UNIQUE,
    location TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    intent TEXT,
    auth_method TEXT,
    similarity_score DOUBLE PRECISION,
    threshold DOUBLE PRECISION,
    result TEXT,
    timestamp TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_schedules_user_start_time
    ON schedules(user_id, start_time);
CREATE INDEX IF NOT EXISTS idx_tasks_user_status_due_date
    ON tasks(user_id, status, due_date);
CREATE INDEX IF NOT EXISTS idx_private_notes_user_id
    ON private_notes(user_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_samples_user_id
    ON enrollment_samples(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_timestamp
    ON audit_logs(user_id, timestamp DESC);

-- No vector index is created yet: current SID computes cosine similarity in
-- Python after loading profiles, so an ANN index would not be used.
