project:
  name: Secure Student Virtual Assistant

speaker:
  model_source: speechbrain/spkrec-ecapa-voxceleb
  sample_rate: 16000
  local_checkpoint: models/ecapa_vietnamceleb_epoch10.pt
  model_cache_dir: models/pretrained_ecapa
  use_vad: true
  vad_source: speechbrain/vad-crdnn-libriparty
  vad_cache_dir: models/vad_crdnn

asr:
  model_size: turbo
  device: cpu
  compute_type: int8
  language: vi
  beam_size: 3

database:
  path: data/app.db
